//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCRAPConveyor.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasculaRevuelta
    {
        public long id { get; set; }
        public Nullable<int> boleto { get; set; }
        public string placas { get; set; }
        public string chofer { get; set; }
        public string usuario { get; set; }
        public string empresa { get; set; }
        public string transportista { get; set; }
        public Nullable<System.DateTime> fechaHoraEntrada { get; set; }
        public Nullable<decimal> pesoEntrada { get; set; }
        public Nullable<System.DateTime> fechaHoraSalida { get; set; }
        public Nullable<decimal> pesoSalida { get; set; }
        public Nullable<decimal> pesoTara { get; set; }
        public Nullable<int> bascula { get; set; }
        public string tagCamion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<bool> factura { get; set; }
        public string numFactura { get; set; }
        public string producto { get; set; }
        public Nullable<bool> documento { get; set; }
        public string numDocumento { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
        public Nullable<bool> correo_enviado { get; set; }
        public Nullable<bool> generar_factura { get; set; }
    }
}
