//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCRAPConveyor.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public long id { get; set; }
        public string tipoMaterial { get; set; }
        public string tolva { get; set; }
        public string descSAP { get; set; }
        public string cortina { get; set; }
        public Nullable<bool> facturado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> boleto { get; set; }
        public Nullable<int> idLinea { get; set; }
        public string material { get; set; }
        public Nullable<int> material2 { get; set; }
    }
}
