//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCRAPConveyor.DB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCRAPConveyorEntities : DbContext
    {
        public SCRAPConveyorEntities()
            : base("name=SCRAPConveyorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TrailerInfoHistory> TrailerInfoHistory { get; set; }
        public virtual DbSet<TrailerInformation> TrailerInformation { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<BasculaRevuelta_Log> BasculaRevuelta_Log { get; set; }
        public virtual DbSet<BasculaRevuelta> BasculaRevuelta { get; set; }
        public virtual DbSet<PrecioSCRAP> PrecioSCRAP { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
    }
}
