//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCRAPConveyor.DB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCRAPConveyorEntities : DbContext
    {
        public SCRAPConveyorEntities()
            : base("name=SCRAPConveyorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<BasculaRevuelta_Log> BasculaRevuelta_Log { get; set; }
        public virtual DbSet<BasculaRevuelta> BasculaRevuelta { get; set; }
        public virtual DbSet<PrecioSCRAP> PrecioSCRAP { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<TrailerInformation> TrailerInformation { get; set; }
    
        public virtual ObjectResult<sp_GetList_HistoryReport_Result> sp_GetList_HistoryReport(Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin)
        {
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetList_HistoryReport_Result>("sp_GetList_HistoryReport", fecha_inicioParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<string> spSendMail_SCRAPConveyor_FacturaAutomatica(Nullable<int> boleto)
        {
            var boletoParameter = boleto.HasValue ?
                new ObjectParameter("boleto", boleto) :
                new ObjectParameter("boleto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spSendMail_SCRAPConveyor_FacturaAutomatica", boletoParameter);
        }
    
        public virtual ObjectResult<sp_GetList_BasculasFactura_Result> sp_GetList_BasculasFactura(Nullable<int> boleto, Nullable<int> idLinea)
        {
            var boletoParameter = boleto.HasValue ?
                new ObjectParameter("boleto", boleto) :
                new ObjectParameter("boleto", typeof(int));
    
            var idLineaParameter = idLinea.HasValue ?
                new ObjectParameter("idLinea", idLinea) :
                new ObjectParameter("idLinea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetList_BasculasFactura_Result>("sp_GetList_BasculasFactura", boletoParameter, idLineaParameter);
        }
    }
}
